---

# lighttpd-gunicorn-flask
lgf_supervisor_password: "05444515-6B85-406E-AF17-6B87D1A07B63"

lgf_app:
  - server_name: "med-service"
    flask_app: "wsgi"
    proxy_port: "8000"
    gunicorn_port: "18000"
    gunicorn_threads: "3"
    app_dir: "/var/www/html/medication-service"
    virtualenv_dir: "/var/www/html/medication-service/env"
    media_dir: ""
    python_3: true
    repo: "git@github.com:chb/medication-service"
    ssh_keyfile: "deploy_key.service"
    extra_files:
      - src: "config.service.py"
        dest: "config.py"

  - server_name: "med-app"
    flask_app: "wsgi"
    gunicorn_port: "10080"
    gunicorn_threads: "3"
    app_dir: "/var/www/html/medication-app"
    virtualenv_dir: "/var/www/html/medication-app/env"
    media_dir: ""
    python_3: true
    repo: "git@github.com:chb/medication-app"
    ssh_keyfile: "deploy_key.app"
    extra_files:
      - src: "config.app.py"
        dest: "config.py"
